import type { DB } from "@db/generated/zod";
import type { JSX } from "solid-js";
import { Icons } from "..";

export const TableIconMap: Record<keyof DB, JSX.Element> = {
	account: <Icons.Filled.Category2 />,
	account_create_data: undefined,
	account_update_data: undefined,
	activity: undefined,
	address: undefined,
	armor: undefined,
	_armorTocrystal: undefined,
	avatar: undefined,
	_avatarTocharacter: undefined,
	_backRelation: undefined,
	_campA: undefined,
	_campB: undefined,
	character: undefined,
	character_skill: undefined,
	_characterToconsumable: undefined,
	combo: undefined,
	combo_step: undefined,
	consumable: undefined,
	crystal: undefined,
	_crystalTooption: undefined,
	_crystalToplayer_armor: undefined,
	_crystalToplayer_option: undefined,
	_crystalToplayer_special: undefined,
	_crystalToplayer_weapon: undefined,
	_crystalTospecial: undefined,
	_crystalToweapon: undefined,
	drop_item: undefined,
	_frontRelation: undefined,
	image: undefined,
	item: undefined,
	_linkZones: undefined,
	material: undefined,
	member: undefined,
	mercenary: undefined,
	mob: undefined,
	_mobTozone: undefined,
	npc: undefined,
	option: undefined,
	player: undefined,
	player_armor: undefined,
	player_option: undefined,
	player_pet: undefined,
	player_special: undefined,
	player_weapon: undefined,
	post: undefined,
	recipe: undefined,
	recipe_ingredient: undefined,
	session: undefined,
	simulator: undefined,
	skill: undefined,
	skill_variant: undefined,
	special: undefined,
	statistic: undefined,
	task: undefined,
	task_collect_require: undefined,
	task_kill_requirement: undefined,
	task_reward: undefined,
	team: undefined,
	user: undefined,
	verification_token: undefined,
	weapon: undefined,
	world: undefined,
	zone: undefined,
};
