# 后端服务镜像配置文件，将会运行一个 PostgreSQL 数据库和一个 Electric 服务
name: "toram-calculator"

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${PG_DBNAME}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - ${PG_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/generated/serverDB/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./healthcheck.sh:/usr/local/bin/healthcheck.sh
    command:
      - -c
      - listen_addresses=*
      - -c
      - wal_level=logical
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 120s

  electric:
    image: electricsql/electric
    environment:
      DATABASE_URL: postgresql://${PG_USERNAME}:${PG_PASSWORD}@postgres:${PG_PORT}/${PG_DBNAME}?sslmode=disable
      # Not suitable for production. Only use insecure mode in development or if you've otherwise secured the Electric API.
      # See https://electric-sql.com/docs/guides/security
      ELECTRIC_INSECURE: true
    ports:
      - ${ELECTRIC_PORT}:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
