export enum ModifierType {
  DEFAULT,
  // 能力值
  STR, // 力量
  INT, // 智力
  VIT, // 耐力
  AGI, // 敏捷
  DEX, // 灵巧
  // 基础属性
  MAX_MP, // 最大MP
  AGGRO, // 仇恨值
  WEAPON_RANGE, // 武器射程
  HP_REGEN, // HP自然回复
  MP_REGEN, // MP自然回复
  // 单次伤害增幅
  PHYSICAL_ATK, // 物理攻击
  MAGICAL_ATK, // 魔法攻击
  WEAPON_ATK, // 武器攻击
  UNSHEATHE_ATK, // 拔刀攻击
  PHYSICAL_PIERCE, // 物理贯穿
  MAGICAL_PIERCE, // 魔法贯穿
  CRITICAL_RATE, // 暴击率
  CRITICAL_DAMAGE, // 暴击伤害
  MAGIC_CRT_CONVERSION_RATE, // 魔法暴击转化率
  MAGIC_CRT_DAMAGE_CONVERSION_RATE, // 魔法爆伤转化率
  SHORT_RANGE_DAMAGE, // 近距离威力
  LONG_RANGE_DAMAGE, // 远距离威力
  STRONGER_AGAINST_NETURAL, // 对无属性增强
  STRONGER_AGAINST_LIGHT, // 对光属性增强
  STRONGER_AGAINST_DARK, // 对暗属性增强
  STRONGER_AGAINST_WATER, // 对水属性增强
  STRONGER_AGAINST_FIRE, // 对火属性增强
  STRONGER_AGAINST_EARTH, // 对地属性增强
  STRONGER_AGAINST_WIND, // 对风属性增强
  STABILITY, // 稳定率
  ACCURACY, // 命中
  ADDITIONAL_PHYSICS, // 物理追击
  ADDITIONAL_MAGIC, // 魔法追击
  ANTICIPATE, // 看穿
  GUARD_BREAK, // 破防
  REFLECT, // 反弹伤害
  ABSOLUTA_ACCURACY, // 绝对命中
  ATK_UP_STR, // 物理攻击提升（力量）
  ATK_UP_INT, // 物理攻击提升（智力）
  ATK_UP_VIT, // 物理攻击提升（耐力）
  ATK_UP_AGI, // 物理攻击提升（敏捷）
  ATK_UP_DEX, // 物理攻击提升（灵巧）
  MATK_UP_STR, // 魔法攻击提升（力量）
  MATK_UP_INT, // 魔法攻击提升（智力）
  MATK_UP_VIT, // 魔法攻击提升（耐力）
  MATK_UP_AGI, // 魔法攻击提升（敏捷）
  MATK_UP_DEX, // 魔法攻击提升（灵巧）
  ATK_DOWN_STR, // 物理攻击下降（力量）
  ATK_DOWN_INT, // 物理攻击下降（智力）
  ATK_DOWN_VIT, // 物理攻击下降（耐力）
  ATK_DOWN_AGI, // 物理攻击下降（敏捷）
  ATK_DOWN_DEX, // 物理攻击下降（灵巧）
  MATK_DOWN_STR, // 魔法攻击下降（力量）
  MATK_DOWN_INT, // 魔法攻击下降（智力）
  MATK_DOWN_VIT, // 魔法攻击下降（耐力）
  MATK_DOWN_AGI, // 魔法攻击下降（敏捷）
  MATK_DOWN_DEX, // 魔法攻击下降（灵巧）
  // 生存能力加成
  MAX_HP, // 最大HP
  PHYSICAL_DEF, // 物理防御
  MAGICAL_DEF, // 魔法防御
  PHYSICAL_RESISTANCE, // 物理抗性
  MAGICAL_RESISTANCE, // 魔法抗性
  NEUTRAL_RESISTANCE, // 无属性抗性
  LIGHT_RESISTANCE, // 光属性抗性
  DARK_RESISTANCE, // 暗属性抗性
  WATER_RESISTANCE, // 水属性抗性
  FIRE_RESISTANCE, // 火属性抗性
  EARTH_RESISTANCE, // 地属性抗性
  WIND_RESISTANCE, // 风属性抗性
  DODGE, // 回避
  AILMENT_RESISTANCE, // 异常抗性
  BASE_GUARD_POWER, // 基础格挡力
  GUARD_POWER, // 格挡力
  BASE_GUARD_RECHARGE, // 基础格挡回复
  GUARD_RECHANGE, // 格挡回复
  EVASION_RECHARGE, // 闪躲回复
  PHYSICAL_BARRIER, // 物理屏障
  MAGICAL_BARRIER, // 魔法屏障
  FRACTIONAL_BARRIER, // 百分比瓶屏障
  BARRIER_COOLDOWN, // 屏障回复速度
  REDUCE_DMG_FLOOR, // 地面伤害减轻（地刺）
  REDUCE_DMG_METEOR, // 陨石伤害减轻（天火）
  REDUCE_DMG_PLAYER_EPICENTER, // 范围伤害减轻（以玩家为中心的范围伤害）
  REDUCE_DMG_FOE_EPICENTER, // 敌方周围伤害减轻（以怪物自身为中心的范围伤害）
  REDUCE_DMG_BOWLING, // 贴地伤害减轻（剑气、风刃）
  REDUCE_DMG_BULLET, // 子弹伤害减轻（各种球）
  REDUCE_DMG_STRAIGHT_LINE, // 直线伤害减轻（激光）
  REDUCE_DMG_CHARGE, // 冲撞伤害减轻（怪物的位移技能）
  ABSOLUTE_DODGE, // 绝对回避
  // 速度加成
  ASPD, // 攻击速度
  CSPD, // 咏唱速度
  MSPD, // 行动速度
  // 其他加成
  DROP_RATE, // 掉宝率
  REVIVE_TIME, // 复活时间
  FLINCH_UNAVAILABLE, // 封印胆怯
  TUMBLE_UNAVAILABLE, // 封印翻覆
  STUN_UNAVAILABLE, // 封印昏厥
  INVINCIBLE_AID, // 无敌急救
  EXP_RATE, // 经验加成
  PET_EXP, // 宠物经验
  ITEM_COOLDOWN, // 道具冷却
  RECOIL_DAMAGE, // 反作用伤害
  GEM_POWDER_DROP, // 晶石粉末掉落
}

export enum CharacterModifierType {
  default,
  str, // 力量
  int, // 智力
  vit, // 耐力
  agi, // 敏捷
  dex, // 灵巧
  maxMp, // 最大MP
  aggro, // 仇恨值
  weaponRange, // 武器射程
  hpRegen, // HP自然回复
  mpRegen, // MP自然回复
  physicalAtk, // 物理攻击
  magicalAtk, // 魔法攻击
  weaponAtk, // 武器攻击
  unsheatheAtk, // 拔刀攻击
  physicalPierce, // 物理贯穿
  magicalPierce, // 魔法贯穿
  criticalRate, // 暴击率
  criticalDamage, // 暴击伤害
  magicCrtConversionRate, // 魔法暴击转化率
  magicCrtDamageConversionRate, // 魔法爆伤转化率
  shortRangeDamage, // 近距离威力
  longRangeDamage, // 远距离威力
  strongerAgainstNetural, // 对无属性增强
  strongerAgainstLight, // 对光属性增强
  strongerAgainstDark, // 对暗属性增强
  strongerAgainstWater, // 对水属性增强
  strongerAgainstFire, // 对火属性增强
  strongerAgainstEarth, // 对地属性增强
  strongerAgainstWind, // 对风属性增强
  stability, // 稳定率
  accuracy, // 命中
  additionalPhysics, // 物理追击
  additionalMagic, // 魔法追击
  anticipate, // 看穿
  guardBreak, // 破防
  reflect, // 反弹伤害
  absolutaAccuracy, // 绝对命中
  atkUpStr, // 物理攻击提升（力量）
  atkUpInt, // 物理攻击提升（智力）
  atkUpVit, // 物理攻击提升（耐力）
  atkUpAgi, // 物理攻击提升（敏捷）
  atkUpDex, // 物理攻击提升（灵巧）
  matkUpStr, // 魔法攻击提升（力量）
  matkUpInt, // 魔法攻击提升（智力）
  matkUpVit, // 魔法攻击提升（耐力）
  matkUpAgi, // 魔法攻击提升（敏捷）
  matkUpDex, // 魔法攻击提升（灵巧）
  atkDownStr, // 物理攻击下降（力量）
  atkDownInt, // 物理攻击下降（智力）
  atkDownVit, // 物理攻击下降（耐力）
  atkDownAgi, // 物理攻击下降（敏捷）
  atkDownDex, // 物理攻击下降（灵巧）
  matkDownStr, // 魔法攻击下降（力量）
  matkDownInt, // 魔法攻击下降（智力）
  matkDownVit, // 魔法攻击下降（耐力）
  matkDownAgi, // 魔法攻击下降（敏捷）
  matkDownDex, // 魔法攻击下降（灵巧）
  maxHp, // 最大HP
  physicalDef, // 物理防御
  magicalDef, // 魔法防御
  physicalResistance, // 物理抗性
  magicalResistance, // 魔法抗性
  neutralResistance, // 无属性抗性
  lightResistance, // 光属性抗性
  darkResistance, // 暗属性抗性
  waterResistance, // 水属性抗性
  fireResistance, // 火属性抗性
  earthResistance, // 地属性抗性
  windResistance, // 风属性抗性
  dodge, // 回避
  ailmentResistance, // 异常抗性
  baseGuardPower, // 基础格挡力
  guardPower, // 格挡力
  baseGuardRecharge, // 基础格挡回复
  guardRechange, // 格挡回复
  evasionRecharge, // 闪躲回复
  physicalBarrier, // 物理屏障
  magicalBarrier, // 魔法屏障
  fractionalBarrier, // 百分比屏障
  barrierCooldown, // 屏障回复速度
  reduceDmgFloor, // 地面伤害减轻（地刺）
  reduceDmgMeteor, // 陨石伤害减轻（天火）
  reduceDmgPlayerEpicenter, // 范围伤害减轻（以玩家为中心的范围伤害）
  reduceDmgFoeEpicenter, // 敌方周围伤害减轻（以怪物自身为中心的范围伤害）
  reduceDmgBowling, // 贴地伤害减轻（剑气、风刃）
  reduceDmgBullet, // 子弹伤害减轻（各种球）
  reduceDmgStraightLine, // 直线伤害减轻（激光）
  reduceDmgCharge, // 冲撞伤害减轻（怪物的位移技能）
  absoluteDodge, // 绝对回避
  aspd, // 攻击速度
  cspd, // 咏唱速度
  mspd, // 行动速度
  dropRate, // 掉宝率
  reviveTime, // 复活时间
  flinchUnavailable, // 封印胆怯
  tumbleUnavailable, // 封印翻覆
  stunUnavailable, // 封印昏厥
  invincibleAid, // 无敌急救
  expRate, // 经验加成
  petExp, // 宠物经验
  itemCooldown, // 道具冷却
  recoilDamage, // 反作用伤害
  gemPowderDrop, // 晶石粉末掉落
}

export enum MonsterModifierType {
  default,
  physicalAtk, // 物理攻击
  magicalAtk, // 魔法攻击
  criticalRate, // 暴击率
  criticalDamage, // 暴击伤害
  stability, // 稳定率
  accuracy, // 命中
  maxHp, // 最大HP
  physicalDef, // 物理防御
  magicalDef, // 魔法防御
  physicalResistance, // 物理抗性
  magicalResistance, // 魔法抗性
  neutralResistance, // 无属性抗性
  lightResistance, // 光属性抗性
  darkResistance, // 暗属性抗性
  waterResistance, // 水属性抗性
  fireResistance, // 火属性抗性
  earthResistance, // 地属性抗性
  windResistance, // 风属性抗性
  dodge, // 回避
  ailmentResistance, // 异常抗性
  baseGuardPower, // 基础格挡力
  guardPower, // 格挡力
  baseGuardRecharge, // 基础格挡回复
  guardRechange, // 格挡回复
  evasionRecharge, // 闪躲回复
  aspd, // 攻击速度
  cspd, // 咏唱速度
  mspd, // 行动速度
}

export enum SkillModifierType {
    
}