import { Selectable } from "kysely";
import { DB } from "./generated/zod/index";

type SelectDB<T> = {
  [K in keyof T]: Selectable<T[K]>;
};

export const defaultData: SelectDB<DB> = {
  _armorTocrystal: {
    A: "",
    B: "",
  },
  _avatarTocharacter: {
    A: "",
    B: "",
  },
  _backRelation: {
    A: "",
    B: "",
  },
  _campA: {
    A: "",
    B: "",
  },
  _campB: {
    A: "",
    B: "",
  },
  _characterToconsumable: {
    A: "",
    B: "",
  },
  _crystalTooption: {
    A: "",
    B: "",
  },
  _crystalToplayer_armor: {
    A: "",
    B: "",
  },
  _crystalToplayer_option: {
    A: "",
    B: "",
  },
  _crystalToplayer_special: {
    A: "",
    B: "",
  },
  _crystalToplayer_weapon: {
    A: "",
    B: "",
  },
  _crystalTospecial: {
    A: "",
    B: "",
  },
  _crystalToweapon: {
    A: "",
    B: "",
  },
  _frontRelation: {
    A: "",
    B: "",
  },
  _linkZones: {
    A: "",
    B: "",
  },
  _mobTozone: {
    A: "",
    B: "",
  },
  account: {
    id: "defaultAccountId",
    type: "User",
    provider: "",
    providerAccountId: "",
    refresh_token: undefined,
    access_token: undefined,
    expires_at: undefined,
    token_type: undefined,
    scope: undefined,
    id_token: undefined,
    session_state: undefined,
    userId: undefined,
  },
  account_create_data: {
    accountId: "defaultAccountId",
  },
  account_update_data: {
    accountId: "defaultAccountId",
  },
  activity: {
    id: "defaultActivityId",
    name: "默认活动",
    statisticId: "defaultActivityStatisticId",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  address: {
    id: "defaultAddressId",
    name: "默认地址",
    type: "Normal",
    posX: 0,
    posY: 0,
    worldId: "",
    statisticId: "defaultAddressStatisticId",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  armor: {
    name: "默认防具",
    baseAbi: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    itemId: "defaultArmorItemId",
  },
  avatar: {
    id: "defaultAvatarId",
    name: "默认时装",
    type: "Decoration",
    modifiers: [],
    belongToPlayerId: "defaultAvatarPlayerId",
  },
  character: {
    id: "defaultCharacterId",
    name: "默认机体",
    lv: 0,
    str: 0,
    int: 0,
    vit: 0,
    agi: 0,
    dex: 0,
    personalityType: "None",
    personalityValue: 0,
    weaponId: undefined,
    subWeaponId: undefined,
    armorId: undefined,
    optionId: undefined,
    specialId: undefined,
    cooking: [],
    modifiers: [],
    partnerSkillAId: undefined,
    partnerSkillAType: "Passive",
    partnerSkillBId: undefined,
    partnerSkillBType: "Passive",
    belongToPlayerId: "defaultPlayerId",
    details: undefined,
    statisticId: "defaultCharacterStatisticId",
  },
  character_skill: {
    id: "defaultCharacterSkillId",
    lv: 0,
    isStarGem: false,
    templateId: "",
    belongToCharacterId: "defaultCharacterId",
  },
  combo: {
    id: "defaultComboId",
    disable: false,
    name: "默认连击",
    belongToCharacterId: "defaultCharacterId",
  },
  combo_step: {
    id: "defaultComboStepId",
    type: "None",
    characterSkillId: "defaultCharacterSkillId",
    belongToComboId: "defaultComboId",
  },
  consumable: {
    name: "默认消耗品",
    type: "MaxHp",
    effectDuration: 0,
    effects: [],
    itemId: "defaultConsumableItemId",
  },
  crystal: {
    name: "默认水晶",
    type: "NormalCrystal",
    modifiers: [],
    itemId: "defaultCrystalItemId",
  },
  drop_item: {
    id: "defaultDropItemId",
    itemId: "defaultDropItemItemId",
    belongToMobId: "",
    breakRewardType: "None",
    relatedPartType: "A",
    relatedPartInfo: "defaultDropItemRelatedPartInfo",
    probability: 0,
  },
  image: {
    id: "defaultImageId",
    dataUrl: "defaultImageDataUrl",
    belongToNpcId: undefined,
    weaponId: undefined,
    armorId: undefined,
    optionId: undefined,
    mobId: undefined,
  },
  item: {
    id: "defaultItemId",
    itemType: "Weapon",
    name: "默认物品",
    dataSources: "",
    details: undefined,
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
    itemSourceType: "Player",
  },
  material: {
    name: "默认材料",
    type: "Metal",
    ptValue: 0,
    price: 0,
    itemId: "",
  },
  member: {
    id: "defaultMemberId",
    name: "",
    sequence: 0,
    playerId: undefined,
    partnerId: undefined,
    mercenaryId: undefined,
    mobId: undefined,
    mobDifficultyFlag: "Normal",
    actions: undefined,
    belongToTeamId: "",
    type: "Mob",
  },
  mercenary: {
    type: "Tank",
    templateId: "",
    skillAId: "",
    skillAType: "Passive",
    skillBId: "",
    skillBType: "Passive",
  },
  mob: {
    id: "defaultMobId",
    name: "",
    type: "Boss",
    captureable: false,
    baseLv: 0,
    experience: 0,
    partsExperience: 0,
    initialElement: "Normal",
    radius: 0,
    maxhp: 0,
    physicalDefense: 0,
    physicalResistance: 0,
    magicalDefense: 0,
    magicalResistance: 0,
    criticalResistance: 0,
    avoidance: 0,
    dodge: 0,
    block: 0,
    normalDefExp: 0,
    physicDefExp: 0,
    magicDefExp: 0,
    actions: {},
    details: "",
    dataSources: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  npc: {
    id: "defaultNpcId",
    name: "",
    zoneId: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  option: {
    name: "默认追加",
    baseAbi: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    itemId: "",
  },
  player: {
    id: "defaultPlayerId",
    name: "",
    useIn: "",
    belongToAccountId: "defaultAccountId",
  },
  player_armor: {
    id: "defaultPlayerArmorId",
    name: "",
    extraAbi: 0,
    ability: "Normal",
    templateId: undefined,
    refinement: 0,
    modifiers: [],
    belongToPlayerId: "defaultPlayerId",
    baseAbi: 0,
  },
  player_option: {
    id: "defaultPlayerOptionId",
    name: "",
    extraAbi: 0,
    templateId: "",
    refinement: 0,
    belongToPlayerId: "defaultPlayerId",
    baseAbi: 0,
    modifiers: [],
  },
  player_pet: {
    id: "defaultPlayerPetId",
    templateId: "",
    name: "",
    pStr: 0,
    pInt: 0,
    pVit: 0,
    pAgi: 0,
    pDex: 0,
    str: 0,
    int: 0,
    vit: 0,
    agi: 0,
    dex: 0,
    weaponType: "OneHandSword",
    personaType: "Max",
    type: "Hit",
    weaponAtk: 0,
    generation: 0,
    maxLv: 0,
    belongToPlayerId: "defaultPlayerId",
  },
  player_special: {
    id: "defaultPlayerSpecialId",
    name: "",
    extraAbi: 0,
    templateId: "",
    belongToPlayerId: "defaultPlayerId",
    baseAbi: 0,
    modifiers: [],
  },
  player_weapon: {
    id: "defaultPlayerWeaponId",
    name: "",
    baseAbi: 0,
    stability: 0,
    extraAbi: 0,
    templateId: undefined,
    refinement: 0,
    modifiers: [],
    belongToPlayerId: "defaultPlayerId",
    type: "OneHandSword",
    elementType: "Normal",
  },
  post: {
    id: "defaultPostId",
    name: "",
    createdAt: new Date(),
    updatedAt: new Date(),
    createdById: "defaultAccountId",
  },
  recipe: {
    id: "defaultRecipeId",
    itemId: "defaultItemId",
    activityId: undefined,
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  recipe_ingredient: {
    id: "defaultRecipeIngredientId",
    recipeId: "defaultRecipeId",
    type: "Metal",
    itemId: undefined,
    count: 0,
  },
  session: {
    id: "defaultSessionId",
    sessionToken: "",
    expires: new Date(),
    userId: "defaultUserId",
  },
  simulator: {
    id: "defaultSimulatorId",
    name: "",
    details: undefined,
    statisticId: "defaultSimulatorStatisticId",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  skill: {
    id: "defaultSkillId",
    name: "默认技能",
    treeType: "BladeSkill",
    posX: 0,
    posY: 0,
    tier: 0,
    isPassive: false,
    chargingType: "Chanting",
    distanceType: "None",
    targetType: "None",
    details: "默认技能详情",
    dataSources: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  skill_effect: {
    id: "defaultSkillEffectId",
    condition: "",
    elementLogic: "",
    castingRange: "",
    effectiveRange: 0,
    motionFixed: "",
    motionModified: "",
    chantingFixed: "",
    chantingModified: "",
    reservoirFixed: "",
    reservoirModified: "",
    startupFrames: "",
    hpCost: undefined,
    mpCost: "100",
    description: "",
    logic: [],
    details: undefined,
    belongToskillId: "",
  },
  special: {
    name: "默认特殊",
    baseAbi: 0,
    modifiers: [],
    itemId: "",
  },
  statistic: {
    id: "defaultStatisticId",
    updatedAt: new Date(),
    createdAt: new Date(),
    usageTimestamps: [],
    viewTimestamps: [],
  },
  task: {
    id: "defaultTaskId",
    name: "",
    lv: 0,
    type: "Collect",
    description: "",
    belongToNpcId: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  task_collect_require: {
    id: "defaultTaskCollectRequireId",
    count: 0,
    itemId: "",
    belongToTaskId: "",
  },
  task_kill_requirement: {
    id: "defaultTaskKillRequirementId",
    mobId: "",
    count: 0,
    belongToTaskId: "",
  },
  task_reward: {
    id: "defaultTaskRewardId",
    belongToTaskId: "",
    type: "Item",
    value: 0,
    probability: 0,
    itemId: undefined,
  },
  team: {
    id: "defaultTeamId",
    name: undefined,
    gems: [],
  },
  user: {
    id: "defaultUserId",
    name: undefined,
    email: undefined,
    emailVerified: undefined,
    password: undefined,
    image: undefined,
  },
  verification_token: {
    identifier: "defaultVerificationToken",
    token: "",
    expires: new Date(),
  },
  weapon: {
    name: "默认武器",
    type: "OneHandSword",
    baseAbi: 0,
    elementType: "Normal",
    stability: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    itemId: "defaultWeaponItemId",
  },
  world: {
    id: "defaultWorldId",
    name: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
  zone: {
    id: "defaultZoneId",
    name: "",
    rewardNodes: 0,
    activityId: "",
    addressId: "",
    statisticId: "",
    updatedByAccountId: undefined,
    createdByAccountId: undefined,
  },
};
