import { DB } from "./kysely/kyesely";

export const defaultData: DB = {
  _armorTocrystal: {
    A: "",
    B: "",
  },
  _avatarTocharacter: {
    A: "",
    B: "",
  },
  _BackRelation: {
    A: "",
    B: "",
  },
  _campA: {
    A: "",
    B: "",
  },
  _campB: {
    A: "",
    B: "",
  },
  _characterToconsumable: {
    A: "",
    B: "",
  },
  _crystalTooption: {
    A: "",
    B: "",
  },
  _crystalToplayer_armor: {
    A: "",
    B: "",
  },
  _crystalToplayer_option: {
    A: "",
    B: "",
  },
  _crystalToplayer_special: {
    A: "",
    B: "",
  },
  _crystalToplayer_weapon: {
    A: "",
    B: "",
  },
  _crystalTospecial: {
    A: "",
    B: "",
  },
  _crystalToweapon: {
    A: "",
    B: "",
  },
  _FrontRelation: {
    A: "",
    B: "",
  },
  _mobTozone: {
    A: "",
    B: "",
  },
  account: {
    id: "",
    type: "User",
    provider: "",
    providerAccountId: "",
    refresh_token: null,
    access_token: null,
    expires_at: null,
    token_type: null,
    scope: null,
    id_token: null,
    session_state: null,
    userId: null,
  },
  account_create_data: {
    accountId: "",
  },
  account_update_data: {
    accountId: "",
  },
  activity: {
    id: "",
    name: "",
  },
  address: {
    id: "",
    name: "",
    type: "Normal",
    posX: 0,
    posY: 0,
    worldId: "",
  },
  armor: {
    baseDef: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    itemId: "",
  },
  avatar: {
    id: "",
    name: "",
    type: "Decoration",
    modifiers: [],
    playerId: "",
  },
  character: {
    id: "",
    name: "",
    lv: 0,
    str: 0,
    int: 0,
    vit: 0,
    agi: 0,
    dex: 0,
    personalityType: "None",
    personalityValue: 0,
    weaponId: "",
    subWeaponId: "",
    armorId: "",
    optEquipId: "",
    speEquipId: "",
    cooking: [],
    modifiers: [],
    partnerSkillAId: null,
    partnerSkillAType: "Passive",
    partnerSkillBId: null,
    partnerSkillBType: "Passive",
    masterId: "",
    details: null,
    statisticId: "",
  },
  character_skill: {
    id: "",
    lv: 0,
    isStarGem: false,
    templateId: "",
    characterId: "",
  },
  combo: {
    id: "",
    disable: false,
    name: "",
    characterId: "",
  },
  combo_step: {
    id: "",
    type: "None",
    characterSkillId: "",
    comboId: "",
  },
  consumable: {
    type: "MaxHp",
    effectDuration: 0,
    effects: [],
    itemId: "",
  },
  crystal: {
    type: "NormalCrystal",
    modifiers: [],
    itemId: "",
  },
  drop_item: {
    id: "",
    itemId: "",
    probability: 0,
    relatedPartType: "A",
    relatedPartInfo: "",
    breakRewardType: "None",
    dropById: "",
  },
  image: {
    id: "",
    dataUrl: "",
    npcId: null,
    weaponId: null,
    armorId: null,
    optEquipId: null,
    mobId: null,
  },
  item: {
    id: "",
    type: "Weapon",
    name: "",
    dataSources: "",
    details: null,
    statisticId: "",
    updatedByAccountId: null,
    createdByAccountId: null,
  },
  material: {
    type: "Metal",
    ptValue: 0,
    price: 0,
    itemId: "",
  },
  member: {
    id: "",
    name: "",
    sequence: 0,
    playerId: null,
    partnerId: null,
    mercenaryId: null,
    mobId: null,
    mobDifficultyFlag: "Normal",
    actions: undefined,
    teamId: "",
  },
  mercenary: {
    type: "Tank",
    templateId: "",
    skillAId: "",
    skillAType: "Passive",
    skillBId: "",
    skillBType: "Passive",
  },
  mob: {
    id: "",
    name: "",
    type: "Mob",
    captureable: false,
    baseLv: 0,
    experience: 0,
    partsExperience: 0,
    initialElement: "Normal",
    radius: 0,
    maxhp: 0,
    physicalDefense: 0,
    physicalResistance: 0,
    magicalDefense: 0,
    magicalResistance: 0,
    criticalResistance: 0,
    avoidance: 0,
    dodge: 0,
    block: 0,
    normalAttackResistanceModifier: 0,
    physicalAttackResistanceModifier: 0,
    magicalAttackResistanceModifier: 0,
    actions: undefined,
    details: null,
    dataSources: "",
    statisticId: "",
    updatedByAccountId: null,
    createdByAccountId: null,
  },
  npc: {
    id: "",
    name: "",
    zoneId: "",
  },
  option: {
    baseDef: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    itemId: "",
  },
  player: {
    id: "",
    name: "",
    useIn: "",
    accountId: "",
  },
  player_armor: {
    id: "",
    name: "",
    extraAbi: 0,
    ability: "Normal",
    templateId: null,
    refinement: 0,
    modifiers: [],
    masterId: "",
  },
  player_option: {
    id: "",
    name: "",
    extraAbi: 0,
    templateId: "",
    refinement: 0,
    masterId: "",
  },
  player_pet: {
    id: "",
    templateId: "",
    name: "",
    pStr: 0,
    pInt: 0,
    pVit: 0,
    pAgi: 0,
    pDex: 0,
    str: 0,
    int: 0,
    vit: 0,
    agi: 0,
    dex: 0,
    weaponType: "OneHandSword",
    personaType: "Max",
    type: "Hit",
    weaponAtk: 0,
    generation: 0,
    maxLv: 0,
    masterId: "",
  },
  player_special: {
    id: "",
    name: "",
    extraAbi: 0,
    templateId: "",
    masterId: "",
  },
  player_weapon: {
    id: "",
    name: "",
    baseAbi: 0,
    stability: 0,
    extraAbi: 0,
    templateId: null,
    refinement: 0,
    modifiers: [],
    masterId: "",
  },
  post: {
    id: "",
    name: "",
    createdAt: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
    updatedAt: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
    createdById: "",
  },
  recipe: {
    id: "",
    itemId: "",
    activityId: null,
  },
  recipe_ingredient: {
    id: "",
    count: 0,
    type: "Metal",
    itemId: null,
    recipeId: "",
  },
  session: {
    id: "",
    sessionToken: "",
    expires: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
    userId: "",
  },
  simulator: {
    id: "",
    name: "",
    details: null,
    statisticId: "",
    updatedByAccountId: null,
    createdByAccountId: null,
  },
  skill: {
    id: "",
    treeType: "BladeSkill",
    posX: 0,
    posY: 0,
    tier: 0,
    name: "",
    isPassive: false,
    chargingType: "Chanting",
    distanceType: "None",
    targetType: "None",
    details: "",
    dataSources: "",
    statisticId: "",
    updatedByAccountId: null,
    createdByAccountId: null,
  },
  skill_effect: {
    id: "",
    condition: "",
    elementLogic: "",
    castingRange: 0,
    effectiveRange: 0,
    motionFixed: "",
    motionModified: "",
    chantingFixed: "",
    chantingModified: "",
    reservoirFixed: "",
    reservoirModified: "",
    startupFrames: "",
    cost: "",
    description: "",
    logic: undefined,
    details: null,
    belongToskillId: "",
  },
  special: {
    baseDef: 0,
    modifiers: [],
    itemId: "",
  },
  statistic: {
    id: "",
    updatedAt: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
    createdAt: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
    usageTimestamps: [],
    viewTimestamps: [],
  },
  task: {
    id: "",
    lv: 0,
    name: "",
    type: "Collect",
    description: "",
    npcId: "",
  },
  task_collect_require: {
    id: "",
    count: 0,
    itemId: "",
    taskId: "",
  },
  task_kill_requirement: {
    id: "",
    mobId: "",
    count: 0,
    taskId: "",
  },
  task_reward: {
    id: "",
    type: "Item",
    value: 0,
    probability: 0,
    itemId: null,
    taskId: "",
  },
  team: {
    id: "",
    name: null,
    gems: [],
  },
  user: {
    id: "",
    name: null,
    email: null,
    emailVerified: null,
    password: null,
    image: null,
  },
  verification_token: {
    identifier: "",
    token: "",
    expires: {
      __select__: new Date(),
      __insert__: "",
      __update__: "",
    },
  },
  weapon: {
    type: "OneHandSword",
    baseAbi: 0,
    stability: 0,
    modifiers: [],
    colorA: 0,
    colorB: 0,
    colorC: 0,
    elementType: "Normal",
    itemId: "",
  },
  world: {
    id: "",
    name: "",
  },
  zone: {
    id: "",
    name: "",
    linkZone: [],
    rewardNodes: null,
    activityId: null,
    addressId: "",
  },
};
