/**
 * @file defaultData.ts
 * @description 数据库数据的缺省值数据
 * @version 1.0.0
 */
// import type { Selectable } from "kysely";
import { skillLogicExample } from "~/components/features/BtEditor/data/SkillExamples";
import type { DB } from "./generated/zod/index";

// type SelectDB<T> = {
// 	[K in keyof T]: Selectable<T[K]>;
// };

export const defaultData: DB = {
	_armorTocrystal: {
		A: "",
		B: "",
	},
	_avatarTocharacter: {
		A: "",
		B: "",
	},
	_backRelation: {
		A: "",
		B: "",
	},
	_campA: {
		A: "",
		B: "",
	},
	_campB: {
		A: "",
		B: "",
	},
	_characterToconsumable: {
		A: "",
		B: "",
	},
	_crystalTooption: {
		A: "",
		B: "",
	},
	_crystalToplayer_armor: {
		A: "",
		B: "",
	},
	_crystalToplayer_option: {
		A: "",
		B: "",
	},
	_crystalToplayer_special: {
		A: "",
		B: "",
	},
	_crystalToplayer_weapon: {
		A: "",
		B: "",
	},
	_crystalTospecial: {
		A: "",
		B: "",
	},
	_crystalToweapon: {
		A: "",
		B: "",
	},
	_frontRelation: {
		A: "",
		B: "",
	},
	_linkZones: {
		A: "",
		B: "",
	},
	_mobTozone: {
		A: "",
		B: "",
	},
	account: {
		id: "defaultAccountId",
		type: "User",
		provider: "",
		providerAccountId: "",
		refresh_token: null,
		access_token: null,
		expires_at: null,
		token_type: null,
		scope: null,
		id_token: null,
		session_state: null,
		userId: null,
	},
	account_create_data: {
		accountId: "defaultAccountId",
	},
	account_update_data: {
		accountId: "defaultAccountId",
	},
	activity: {
		id: "defaultActivityId",
		name: "默认活动",
		statisticId: "defaultActivityStatisticId",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	address: {
		id: "defaultAddressId",
		name: "默认地址",
		type: "Normal",
		posX: 0,
		posY: 0,
		worldId: "",
		statisticId: "defaultAddressStatisticId",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	armor: {
		name: "默认防具",
		baseAbi: 0,
		modifiers: [],
		colorA: 0,
		colorB: 0,
		colorC: 0,
		itemId: "defaultArmorItemId",
	},
	avatar: {
		id: "defaultAvatarId",
		name: "默认时装",
		type: "Decoration",
		modifiers: [],
		belongToPlayerId: "defaultAvatarPlayerId",
	},
	character: {
		id: "defaultCharacterId",
		name: "默认机体",
		lv: 0,
		str: 0,
		int: 0,
		vit: 0,
		agi: 0,
		dex: 0,
		personalityType: "None",
		personalityValue: 0,
		weaponId: null,
		subWeaponId: null,
		armorId: null,
		optionId: null,
		specialId: null,
		cooking: [],
		modifiers: [],
		partnerSkillAId: null,
		partnerSkillAType: "Passive",
		partnerSkillBId: null,
		partnerSkillBType: "Passive",
		belongToPlayerId: "defaultPlayerId",
		details: null,
		statisticId: "defaultCharacterStatisticId",
	},
	character_skill: {
		id: "defaultCharacterSkillId",
		lv: 0,
		isStarGem: false,
		templateId: "",
		belongToCharacterId: "defaultCharacterId",
	},
	combo: {
		id: "defaultComboId",
		disable: false,
		name: "默认连击",
		belongToCharacterId: "defaultCharacterId",
	},
	combo_step: {
		id: "defaultComboStepId",
		type: "None",
		characterSkillId: "defaultCharacterSkillId",
		belongToComboId: "defaultComboId",
	},
	consumable: {
		name: "默认消耗品",
		type: "MaxHp",
		effectDuration: 0,
		effects: [],
		itemId: "defaultConsumableItemId",
	},
	crystal: {
		name: "默认水晶",
		type: "NormalCrystal",
		modifiers: [],
		itemId: "defaultCrystalItemId",
	},
	drop_item: {
		id: "defaultDropItemId",
		itemId: "defaultDropItemItemId",
		belongToMobId: "",
		breakRewardType: "None",
		relatedPartType: "A",
		relatedPartInfo: "defaultDropItemRelatedPartInfo",
		probability: 0,
	},
	image: {
		id: "defaultImageId",
		dataUrl: "defaultImageDataUrl",
		belongToNpcId: null,
		weaponId: null,
		armorId: null,
		optionId: null,
		mobId: null,
	},
	item: {
		id: "defaultItemId",
		itemType: "Weapon",
		name: "默认物品",
		dataSources: "",
		details: null,
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
		itemSourceType: "Player",
	},
	material: {
		name: "默认材料",
		type: "Metal",
		ptValue: 0,
		price: 0,
		itemId: "",
	},
	member: {
		id: "defaultMemberId",
		name: "",
		sequence: 0,
		playerId: null,
		partnerId: null,
		mercenaryId: null,
		mobId: null,
		mobDifficultyFlag: "Normal",
		actions: null,
		belongToTeamId: "",
		type: "Mob",
	},
	mercenary: {
		type: "Tank",
		templateId: "",
		skillAId: "",
		skillAType: "Passive",
		skillBId: "",
		skillBType: "Passive",
	},
	mob: {
		id: "defaultMobId",
		name: "",
		type: "Boss",
		captureable: false,
		baseLv: 0,
		experience: 0,
		partsExperience: 0,
		initialElement: "Normal",
		radius: 0,
		maxhp: 0,
		physicalDefense: 0,
		physicalResistance: 0,
		magicalDefense: 0,
		magicalResistance: 0,
		criticalResistance: 0,
		avoidance: 0,
		dodge: 0,
		block: 0,
		normalDefExp: 0,
		physicDefExp: 0,
		magicDefExp: 0,
		actions: {
			memberType: "Mob",
			name: "default",
			definition: "",
			agent: "",
		},
		details: "",
		dataSources: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	npc: {
		id: "defaultNpcId",
		name: "",
		zoneId: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	option: {
		name: "默认追加",
		baseAbi: 0,
		modifiers: [],
		colorA: 0,
		colorB: 0,
		colorC: 0,
		itemId: "",
	},
	player: {
		id: "defaultPlayerId",
		name: "",
		useIn: "",
		belongToAccountId: "defaultAccountId",
	},
	player_armor: {
		id: "defaultPlayerArmorId",
		name: "",
		extraAbi: 0,
		ability: "Normal",
		templateId: null,
		refinement: 0,
		modifiers: [],
		belongToPlayerId: "defaultPlayerId",
		baseAbi: 0,
	},
	player_option: {
		id: "defaultPlayerOptionId",
		name: "",
		extraAbi: 0,
		templateId: "",
		refinement: 0,
		belongToPlayerId: "defaultPlayerId",
		baseAbi: 0,
		modifiers: [],
	},
	player_pet: {
		id: "defaultPlayerPetId",
		templateId: "",
		name: "",
		pStr: 0,
		pInt: 0,
		pVit: 0,
		pAgi: 0,
		pDex: 0,
		str: 0,
		int: 0,
		vit: 0,
		agi: 0,
		dex: 0,
		weaponType: "OneHandSword",
		personaType: "Max",
		type: "Hit",
		weaponAtk: 0,
		generation: 0,
		maxLv: 0,
		belongToPlayerId: "defaultPlayerId",
	},
	player_special: {
		id: "defaultPlayerSpecialId",
		name: "",
		extraAbi: 0,
		templateId: "",
		belongToPlayerId: "defaultPlayerId",
		baseAbi: 0,
		modifiers: [],
	},
	player_weapon: {
		id: "defaultPlayerWeaponId",
		name: "",
		baseAbi: 0,
		stability: 0,
		extraAbi: 0,
		templateId: null,
		refinement: 0,
		modifiers: [],
		belongToPlayerId: "defaultPlayerId",
		type: "OneHandSword",
		elementType: "Normal",
	},
	post: {
		id: "defaultPostId",
		name: "",
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
		createdById: "defaultAccountId",
	},
	recipe: {
		id: "defaultRecipeId",
		itemId: "defaultItemId",
		activityId: null,
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	recipe_ingredient: {
		id: "defaultRecipeIngredientId",
		recipeId: "defaultRecipeId",
		type: "Metal",
		itemId: null,
		count: 0,
	},
	session: {
		id: "defaultSessionId",
		sessionToken: "",
		expires: new Date().toISOString(),
		userId: "defaultUserId",
	},
	simulator: {
		id: "defaultSimulatorId",
		name: "",
		details: null,
		statisticId: "defaultSimulatorStatisticId",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	skill: {
		id: "defaultSkillId",
		name: "默认技能",
		treeType: "BladeSkill",
		posX: 0,
		posY: 0,
		tier: 0,
		isPassive: false,
		chargingType: "Chanting",
		distanceType: "None",
		targetType: "None",
		details: "默认技能详情",
		dataSources: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	skill_variant: {
		id: "defaultSkillEffectId",
		targetMainWeaponType: null,
		targetSubWeaponType: null,
		targetArmorAbilityType: "Normal",
		activeEffect: {
			memberType: "Player",
			name: "default",
			definition: skillLogicExample.default.definition,
			agent: skillLogicExample.default.agent,
		},
		passiveEffects: [{
			memberType: "Player",
			name: "default",
			definition: skillLogicExample.default.definition,
			agent: skillLogicExample.default.agent,
		}],
		buffs: [{
			memberType: "Player",
			name: "default",
			definition: skillLogicExample.default.definition,
			agent: skillLogicExample.default.agent,
		}],
		elementLogic: "",
		castingRange: "",
		effectiveRange: 0,
		motionFixed: "",
		motionModified: "",
		chantingFixed: "",
		chantingModified: "",
		reservoirFixed: "",
		reservoirModified: "",
		startupFrames: "",
		hpCost: null,
		mpCost: "100",
		description: "",
		details: null,
		belongToskillId: "",
	},
	special: {
		name: "默认特殊",
		baseAbi: 0,
		modifiers: [],
		itemId: "",
	},
	statistic: {
		id: "defaultStatisticId",
		updatedAt: new Date().toISOString(),
		createdAt: new Date().toISOString(),
		usageTimestamps: [],
		viewTimestamps: [],
	},
	task: {
		id: "defaultTaskId",
		name: "",
		lv: 0,
		type: "Collect",
		description: "",
		belongToNpcId: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	task_collect_require: {
		id: "defaultTaskCollectRequireId",
		count: 0,
		itemId: "",
		belongToTaskId: "",
	},
	task_kill_requirement: {
		id: "defaultTaskKillRequirementId",
		mobId: "",
		count: 0,
		belongToTaskId: "",
	},
	task_reward: {
		id: "defaultTaskRewardId",
		belongToTaskId: "",
		type: "Item",
		value: 0,
		probability: 0,
		itemId: null,
	},
	team: {
		id: "defaultTeamId",
		name: null,
		gems: [],
	},
	user: {
		id: "defaultUserId",
		name: null,
		email: null,
		emailVerified: null,
		password: null,
		image: null,
	},
	verification_token: {
		identifier: "defaultVerificationToken",
		token: "",
		expires: new Date().toISOString(),
	},
	weapon: {
		name: "默认武器",
		type: "OneHandSword",
		baseAbi: 0,
		elementType: "Normal",
		stability: 0,
		modifiers: [],
		colorA: 0,
		colorB: 0,
		colorC: 0,
		itemId: "defaultWeaponItemId",
	},
	world: {
		id: "defaultWorldId",
		name: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
	zone: {
		id: "defaultZoneId",
		name: "",
		rewardNodes: 0,
		activityId: "",
		addressId: "",
		statisticId: "",
		updatedByAccountId: null,
		createdByAccountId: null,
	},
};
